project:
  type: website
  output-dir: docs

website:
  title: "Toby Wang's Personal Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Articles
        menu:
          - text: Colonial Origins of Comparative Development
            href: colonial_origins_ex.qmd
          - text: Finding Contaminated Wells in Bangladesh
            href: contaminated_wells_ex.qmd
          - text: File Draw Bias within Academia
            href: filedraw_ex.qmd
          - text: Doing Monte Carlo on a Desert Island
            href: projects.qmd
          - text: Football Markets and the Efficient Market Hypothesis
            href: football_markets_ex.qmd
          - text: Optimal Stopping
            href: optimal_stop_ex.qmd
          - text: The Lumberjack Quant Interview - a Simulation Apprach
            href: Lumberjack.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/tobywang1128/ERM_Toby
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Toby Wang"

format:
  html:
    theme: cerulean
    toc: true

editor: source
