project:
  type: website
  output-dir: docs

website:
  title: "Toby Wang's Personal Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Articles
        menu:
          - text: Colonial Origins
            href: colonial_origins_ex.qmd
          - text: Contaminated Wells
            href: contaminated_wells_ex.qmd
          - text: File Draw
            href: filedraw_ex.qmd
          - text: Projects
            href: projects.qmd
          - text: Football Markets
            href: football_markets_ex.qmd
          - text: Optimal Stop
            href: optimal_stop_ex.qmd
          - text: Lumberjack
            href: Lumberjack.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/tobywang1128/ERM_Toby
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Toby Wang"

format:
  html:
    theme: cerulean
    toc: true

editor: source
