project:
  type: website
  output-dir: docs
  
website:
  title: "Toby Wang's Personal Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - colonial_origins_ex.qmd
      - contaminated_wells_ex.qmd
      - filedraw_ex.qmd
      - football_markets_ex.qmd
      - optimal_stop_ex.qmd
      - Lumberjack.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/tobywang1128/ERM_Toby
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Toby Wang"

format:
  html:
    theme: cerulean
    toc: true

editor: source

