---
title: "Redefining Privilege"
subtitle: "An article I wrote for my undergraduate magazine: The Oasis"
author: "Toby Wang"
format: html
geometry:
  - top=30mm
  - left=20mm
  - heightrounded
editor: visual
---

On Shabbat, Jewish believers meet in a synagogue and each of them makes a confession. First, the rabbi says, "Oh my god I am nobody. God, I am not worthy of your attention." Then, a rich merchant says, "God, I am also a nobody. I am not even worthy of your attention." Finally, a peasant stands up and says, "oh God, I am also a nobody." The rich merchant then kicks the rabbi, and says to him, "who is this guy who can also say he's a nobody?"

Studying at Oxford, we each know this hypocritical virtue signaling all too well. Even though we are incredibly privileged, we at times paint ourselves as victims. We compare our accommodation to those of other universities and proclaim that we are the unfortunate ones who have the small communal kitchens. We tell our friends back home that they couldn't fathom the amount of stress and work we put up with, even if they tried.

And to be frank, why wouldn't we paint ourselves as victims? Boasting about our privileges is unattractive. It shows unawareness and undeservingness of the advantages we receive without merit. Thus, we either paint ourselves as victims or denounce our privileged identities as vices to signal self-awareness. But whether we admit it, we are all both the privileged and the unfortunate. Like many others, I can tell my story before Oxford in two ways. In one version, I spent most of my education in a Chinese public school, where classes were taught in Mandarin. To fulfill my dreams of studying overseas in higher education, I had to, from a young age, learn to read and write English outside of school without direct access to resources such as Google or YouTube. But I can equally describe my childhood as incredibly privileged. My family can afford my education overseas in Oxford and private school in America, a privilege that most of my Chinese friends lack. Both narratives are equally true and not mutually exclusive. They are both parts of who I am and no single narrative tells the whole truth. 

Since "privilege" holds such a negative connotation, we tend to hide our more privileged narratives from others. Showing a lack of privilege is even rewarded institutionally. With American universities admitting students based on "the difficulties we encounter in our life which can be fundamental to later success," applicants are incentivized to paint themselves as victims. Due to the inability to enforce the truthfulness of these personal narratives, candidates are not being held responsible for writing skewed or plainly disingenuous narratives to outcompete other candidates' yearnings for why they also "deserve" a spot. Even if elite institutions are responsible for creating social equity, it is hard to argue against the fact that institutionally rewarding victimhood encourages lying and hypocrisy. What's worse,

setting up institutional selection processes based on victimhood sets a false standard that individuals' privileges can be compared and ranked. In reality, it is hard to compare two completely different stories and then determine who is more deserving of what. There are countless categories, identities, and social groups, between which exist countless statistical differences. To say that some inter-group differences count as a privilege and others don't is incorrect and even dangerous. The challenge of determining one individual's net privilege at one given time is already a daunting task. A beautiful woman may gain many things, material and immaterial, just with her physical attractiveness. Yet when age begins to rob her of that beauty, she may be left unable to cope with the loss of her previous privilege compared with others who have never experienced the benefits of good looks. The attempt to compare privileges between different people, with each in different stages of their respective life cycles, is unrealistic and a self-defeating end. 

The even greater danger of the modern-day definition of privilege is that it gives the self-anointed judges of privilege immense power to invalidate others who are underprivileged in categories that our society chooses to ignore. 

Sure -- white, rich, private-school educated students might be privileged in terms of the help they receive from their school or parents when applying to Oxford, and they should rightfully admit so. But who are we to judge whether these privileges trump all other categories of suffering? -- suffering researched by psychotherapist Prof. Joy Schaverien, who documented the tendencies of emotional detachment, selective amnesia, and substance abuse in adults who went to boarding school from a young age. 

The self-proclaimed judge of privilege chooses to ignore these disparities between private and non-private school students because it does not fit into their narrative. But making the current social narrative of privilege unfalsifiable and therefore sacred is extremely dangerous. Social narratives dictate public policy, which have great consequences that spread through society for generations. 

For instance, the social narrative of climate change brought about carbon taxation and climate activism. Equally, the social narrative of white superiority brought about Jim Crow laws and racial segregation. Politics is indeed downstream from culture, which makes defining culturally sensitive terms like privilege all the more important. 

Social narratives set the agenda for both thought and action. But instead of testing its accuracy against empirical evidence, narratives can be used maliciously for censorship and tyranny when enforced by judges who actively exclude views against it. These judges often resort to violence and oppression. To avoid besmirching the current social narrative of privilege, judges must also invalidate the suffering of the "privileged". They suffer in silence as a result. 

To become a "judge" of privilege also comes with an entrance fee. One first denounces their own privileged identities through virtue signaling -- just like the rabbi and merchant -- publicizing instead the underprivileged parts of their narratives. In fact, we do this every time we say "as a - insert identity - ", followed by accusations, blame, or condemnation of another's identity. The "judge" uses the position of a self-proclaimed victim, oftentimes disingenuously so, as an instrument to justify their newfound power over others. 

This understanding of privilege, where people use their identities to invalidate others, contradicts the fundamental purpose of privilege-checking: to understand identity groups we are not a part of. 

The goal of checking our privileges as a social movement should be a way for more people to understand the predicaments of those around us. This goal is inherently different from one that tolerates and encourages people to compete for and judge who has more privilege based on a bundle of abstract categories -- namely: white, private school educated, rich, maybe even Asian? 

The best way of defining and understanding privilege is what you overlook in your day-to-day life that other people don't get to. We should still listen to people who have different life experiences than ourselves. The idea of privilege should not be a tool to make others feel bad, or a quality that the "privileged" and "undeserving" could never reconcile with. We can always try to understand others' predicaments by drawing from our personal experiences, however different or challenging it may be. 

Defined constructively, privilege helps us better understand the trials and tribulations of people who are not ourselves. It is hard to put yourself in someone else's shoes if you don't understand exactly what being in their shoes entails.
