<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Toby Wang">
<meta name="dcterms.date" content="2023-07-12">

<title>Toby Wang - Bias in the Labor Market</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Toby Wang</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-data-projects-(economtrics" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Data Projects (Economtrics)</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-data-projects-(economtrics">    
        <li>
    <a class="dropdown-item" href="./colonial_origins_ex.html" rel="" target="">
 <span class="dropdown-text">Colonial Origins of Comparative Development</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./contaminated_wells_ex.html" rel="" target="">
 <span class="dropdown-text">Finding Contaminated Wells in Bangladesh</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./filedraw_ex.html" rel="" target="">
 <span class="dropdown-text">File Draw Bias within Academia</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./projects.html" rel="" target="">
 <span class="dropdown-text">Doing Monte Carlo on a Desert Island</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./football_markets_ex.html" rel="" target="">
 <span class="dropdown-text">Football Markets and the Efficient Market Hypothesis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Lumberjack.html" rel="" target="">
 <span class="dropdown-text">The Lumberjack Quant Interview - a Simulation Apprach</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./optimal_stop_ex.html" rel="" target="">
 <span class="dropdown-text">Optimal Stopping</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-data-projects-(finance" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Data Projects (Finance)</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-data-projects-(finance">    
        <li class="dropdown-header">Under Construction</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-other-writing" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Other Writing</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-other-writing">    
        <li>
    <a class="dropdown-item" href="./oasis_priv.html" rel="" target="">
 <span class="dropdown-text">Redefining Privilege</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./oasis_id.html" rel="" target="">
 <span class="dropdown-text">Holding our Identity Lightly</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://mp.weixin.qq.com/s/yway7VRo7AG3FVNXL6cs5g" rel="" target="">
 <span class="dropdown-text">The Last Generation of Beijingers</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://pdflink.to/oxfordtobydiss/" rel="" target="">
 <span class="dropdown-text">Oxford - Dissertation</span></a>
  </li>  
        <li class="dropdown-header">Oxford - Econometrics</li>
    </ul>
  </li>
</ul>
            <div class="quarto-navbar-tools ms-auto">
    <a href="https://twitter.com/" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-twitter"></i></a>
    <a href="https://github.com/tobywang1128/ERM_Toby" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-github"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#q1" id="toc-q1" class="nav-link active" data-scroll-target="#q1">Q1</a></li>
  <li><a href="#q2" id="toc-q2" class="nav-link" data-scroll-target="#q2">Q2</a>
  <ul class="collapse">
  <li><a href="#a" id="toc-a" class="nav-link" data-scroll-target="#a">a)</a></li>
  <li><a href="#b" id="toc-b" class="nav-link" data-scroll-target="#b">b)</a></li>
  <li><a href="#c-add-two-new-columns-to-bm-female-should-take-the-value-true-if-sex-is-female-and-black-should-take-value-true-if-race-is-black." id="toc-c-add-two-new-columns-to-bm-female-should-take-the-value-true-if-sex-is-female-and-black-should-take-value-true-if-race-is-black." class="nav-link" data-scroll-target="#c-add-two-new-columns-to-bm-female-should-take-the-value-true-if-sex-is-female-and-black-should-take-value-true-if-race-is-black.">c) Add two new columns to bm: female should take the value TRUE if sex is female, and black should take value TRUE if race is black.</a></li>
  </ul></li>
  <li><a href="#q3" id="toc-q3" class="nav-link" data-scroll-target="#q3">Q3</a>
  <ul class="collapse">
  <li><a href="#a-1" id="toc-a-1" class="nav-link" data-scroll-target="#a-1">a)</a></li>
  <li><a href="#b-1" id="toc-b-1" class="nav-link" data-scroll-target="#b-1">b)</a></li>
  <li><a href="#c" id="toc-c" class="nav-link" data-scroll-target="#c">c)</a></li>
  </ul></li>
  <li><a href="#q4" id="toc-q4" class="nav-link" data-scroll-target="#q4">Q4</a>
  <ul class="collapse">
  <li><a href="#a-2" id="toc-a-2" class="nav-link" data-scroll-target="#a-2">a)</a></li>
  <li><a href="#b-2" id="toc-b-2" class="nav-link" data-scroll-target="#b-2">b)</a></li>
  <li><a href="#c-1" id="toc-c-1" class="nav-link" data-scroll-target="#c-1">c)</a></li>
  <li><a href="#d" id="toc-d" class="nav-link" data-scroll-target="#d">d)</a></li>
  <li><a href="#e-why-do-we-care-if-sex-education-ofjobs-computerskills-and-yearsexp-are-balanced-across-race" id="toc-e-why-do-we-care-if-sex-education-ofjobs-computerskills-and-yearsexp-are-balanced-across-race" class="nav-link" data-scroll-target="#e-why-do-we-care-if-sex-education-ofjobs-computerskills-and-yearsexp-are-balanced-across-race">e) Why do we care if <em>sex</em>, <em>education</em>, <em>ofjobs</em>, <em>computerskills</em>, and <em>yearsexp</em> are balanced across race?</a></li>
  <li><a href="#f" id="toc-f" class="nav-link" data-scroll-target="#f">f)</a></li>
  </ul></li>
  <li><a href="#q5" id="toc-q5" class="nav-link" data-scroll-target="#q5">Q5</a>
  <ul class="collapse">
  <li><a href="#a-3" id="toc-a-3" class="nav-link" data-scroll-target="#a-3">a)</a></li>
  <li><a href="#b-3" id="toc-b-3" class="nav-link" data-scroll-target="#b-3">b)</a></li>
  <li><a href="#c-2" id="toc-c-2" class="nav-link" data-scroll-target="#c-2">c)</a></li>
  </ul></li>
  <li><a href="#q6" id="toc-q6" class="nav-link" data-scroll-target="#q6">Q6</a>
  <ul class="collapse">
  <li><a href="#test-the-null-hypothesis-that-there-is-no-difference-in-callback-rates-across-black-and-white-sounding-names-against-the-two-sided-alternative.-comment-on-your-results." id="toc-test-the-null-hypothesis-that-there-is-no-difference-in-callback-rates-across-black-and-white-sounding-names-against-the-two-sided-alternative.-comment-on-your-results." class="nav-link" data-scroll-target="#test-the-null-hypothesis-that-there-is-no-difference-in-callback-rates-across-black-and-white-sounding-names-against-the-two-sided-alternative.-comment-on-your-results.">Test the null hypothesis that there is no difference in callback rates across black and white-sounding names against the two-sided alternative. Comment on your results.</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Bias in the Labor Market</h1>
<p class="subtitle lead">Core Empirical Research Methods - Summer Work</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Toby Wang </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 12, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>bm <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">'https://ditraglia.com/data/lakisha_aer.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 4870 Columns: 65
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (10): id, ad, firstname, sex, race, city, kind, expminreq, schoolreq, ow...
dbl (55): education, ofjobs, yearsexp, honors, volunteer, military, empholes...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<section id="q1" class="level2">
<h2 class="anchored" data-anchor-id="q1">Q1</h2>
<p>The research question that the researchers are trying to answer is whether if being black compared to being white alone, irrespective of socioeconomic, education, experience, and other factors, affects hiring decisions. The authors use a RCT that randomly assigns white-sounding and black-sounding names to resumes and send them to newspaper hiring advertisements. The authors find that not only is there a 50-percent gap in callback between a white-sounding and black-sounding name, high-quality resumes compared to low-quality ones have a statistically significant difference in callback rates between white and black applicants. This suggests that the gap between Whites and African Americans widens with resume quality. These observed results do not vary across different sectors.</p>
</section>
<section id="q2" class="level2">
<h2 class="anchored" data-anchor-id="q2">Q2</h2>
<section id="a" class="level3">
<h3 class="anchored" data-anchor-id="a">a)</h3>
<p>Display the tibble bm. How many rows and columns does it have?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(bm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 65
  id    ad    education ofjobs yearsexp honors volunteer military empholes
  &lt;chr&gt; &lt;chr&gt;     &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1 b     1             4      2        6      0         0        0        1
2 b     1             3      3        6      0         1        1        0
3 b     1             4      1        6      0         0        0        0
4 b     1             3      4        6      0         1        0        1
5 b     1             3      3       22      0         0        0        0
6 b     1             4      2        6      1         0        0        0
# ℹ 56 more variables: occupspecific &lt;dbl&gt;, occupbroad &lt;dbl&gt;,
#   workinschool &lt;dbl&gt;, email &lt;dbl&gt;, computerskills &lt;dbl&gt;, specialskills &lt;dbl&gt;,
#   firstname &lt;chr&gt;, sex &lt;chr&gt;, race &lt;chr&gt;, h &lt;dbl&gt;, l &lt;dbl&gt;, call &lt;dbl&gt;,
#   city &lt;chr&gt;, kind &lt;chr&gt;, adid &lt;dbl&gt;, fracblack &lt;dbl&gt;, fracwhite &lt;dbl&gt;,
#   lmedhhinc &lt;dbl&gt;, fracdropout &lt;dbl&gt;, fraccolp &lt;dbl&gt;, linc &lt;dbl&gt;, col &lt;dbl&gt;,
#   expminreq &lt;chr&gt;, schoolreq &lt;chr&gt;, eoe &lt;dbl&gt;, parent_sales &lt;dbl&gt;,
#   parent_emp &lt;dbl&gt;, branch_sales &lt;dbl&gt;, branch_emp &lt;dbl&gt;, fed &lt;dbl&gt;, …</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(bm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4870</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ncol</span>(bm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 65</code></pre>
</div>
</div>
<p>We see from these commands that the tibble has 4870 rows and 65 columns</p>
</section>
<section id="b" class="level3">
<h3 class="anchored" data-anchor-id="b">b)</h3>
<p>Display only the columns <em>sex</em>, <em>race</em> and <em>firstname</em> of <em>bm</em>. What information do these columns contain? How are <em>sex</em> and <em>race</em> encoded?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>bm <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(sex, race, firstname) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4,870 × 3
   sex   race  firstname
   &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;    
 1 f     w     Allison  
 2 f     w     Kristen  
 3 f     b     Lakisha  
 4 f     b     Latonya  
 5 f     w     Carrie   
 6 m     w     Jay      
 7 f     w     Jill     
 8 f     b     Kenya    
 9 f     b     Latonya  
10 m     b     Tyrone   
# ℹ 4,860 more rows</code></pre>
</div>
</div>
<p>This tibble contains the sex, race of the individual corresponding to their first name. <em>sex</em> is encoded as <strong>m</strong> for male and <strong>f</strong> for female. <em>race</em> is encoded as <strong>w</strong> for white and <strong>b</strong> for black.</p>
</section>
<section id="c-add-two-new-columns-to-bm-female-should-take-the-value-true-if-sex-is-female-and-black-should-take-value-true-if-race-is-black." class="level3">
<h3 class="anchored" data-anchor-id="c-add-two-new-columns-to-bm-female-should-take-the-value-true-if-sex-is-female-and-black-should-take-value-true-if-race-is-black.">c) Add two new columns to bm: female should take the value TRUE if sex is female, and black should take value TRUE if race is black.</h3>
<p>To do this we need to create logic vectors and test (iterate) through the sex and race columns to determine if each other them are female or black. Then we use <em>mutate()</em> to add the two columns in the tibble.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>sex_f <span class="ot">&lt;-</span> bm[[<span class="st">"sex"</span>]] <span class="sc">==</span> <span class="st">"f"</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>race_b <span class="ot">&lt;-</span> bm[[<span class="st">"race"</span>]] <span class="sc">==</span> <span class="st">"b"</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>bm <span class="sc">|&gt;</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(sex, race, firstname)<span class="sc">|&gt;</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(sex_f, race_b)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4,870 × 5
   sex   race  firstname sex_f race_b
   &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;     &lt;lgl&gt; &lt;lgl&gt; 
 1 f     w     Allison   TRUE  FALSE 
 2 f     w     Kristen   TRUE  FALSE 
 3 f     b     Lakisha   TRUE  TRUE  
 4 f     b     Latonya   TRUE  TRUE  
 5 f     w     Carrie    TRUE  FALSE 
 6 m     w     Jay       FALSE FALSE 
 7 f     w     Jill      TRUE  FALSE 
 8 f     b     Kenya     TRUE  TRUE  
 9 f     b     Latonya   TRUE  TRUE  
10 m     b     Tyrone    FALSE TRUE  
# ℹ 4,860 more rows</code></pre>
</div>
</div>
</section>
</section>
<section id="q3" class="level2">
<h2 class="anchored" data-anchor-id="q3">Q3</h2>
<section id="a-1" class="level3">
<h3 class="anchored" data-anchor-id="a-1">a)</h3>
<p>How did the experimenters create their bank of resumes for the experiment?</p>
<p>The experimenters started with resumes of actual job searchers but alter them sufficiently to create distinct resumes. The actual job resumes were taken from two job search websites that posts resumes of applicants seeking jobs in Boston and Chicago, with some further occupational and application time constraints.</p>
</section>
<section id="b-1" class="level3">
<h3 class="anchored" data-anchor-id="b-1">b)</h3>
<p>The experimenters classified the resumes into two groups. What were they and how did they make the classification?</p>
<p>The two groups were: high quality and low quality applicants. The distinction is based on criteria such as labor market experience, career profile, existence of gaps in employment, ans skills listed. Additionally, the researchers also added to the high quality applicants a subset of features such as: pre-employment experience, volunteering experience, extra skills, honors, or military service.</p>
</section>
<section id="c" class="level3">
<h3 class="anchored" data-anchor-id="c">c)</h3>
<p>How did the experimenters generate identities for their fictitious job applicants?</p>
<p>The experimenters used name frequency data calculated from birth certificates of all babies born in Massachusetts between 1974 and 1979. They then tabulate the data by race to determine which names are distinctively White and African American, then they use the most instinctive, highest frequency names of both races on the resumes.</p>
</section>
</section>
<section id="q4" class="level2">
<h2 class="anchored" data-anchor-id="q4">Q4</h2>
<section id="a-2" class="level3">
<h3 class="anchored" data-anchor-id="a-2">a)</h3>
<p>Is sex balanced across race?</p>
<p>We can first use the <em>group_by</em> function to sort the tibble by race then sum the number of females in each race bracket via the variable we created in the first part of the sheet <em>sex_f</em>. Summing the logicals treates each TRUE as a 1 and FALSE as 0.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>bm <span class="sc">|&gt;</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(race)<span class="sc">|&gt;</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">sum_of_f =</span> <span class="fu">sum</span>(sex_f))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  race  sum_of_f
  &lt;chr&gt;    &lt;int&gt;
1 b         3746
2 w         3746</code></pre>
</div>
</div>
<p>We find that the number of males and females are the same across the two racial groups, which means that sex is balanced across race.</p>
</section>
<section id="b-2" class="level3">
<h3 class="anchored" data-anchor-id="b-2">b)</h3>
<p>Are computer skills balanced across race?</p>
<p>To calculate proportion we just take the average across the two groups:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>bm <span class="sc">|&gt;</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(race)<span class="sc">|&gt;</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">prop_comp =</span> <span class="fu">mean</span>(computerskills))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  race  prop_comp
  &lt;chr&gt;     &lt;dbl&gt;
1 b         0.832
2 w         0.809</code></pre>
</div>
</div>
<p>This shows that the white group has a bit less than the black group, but it is probably not significant as it is a difference of 3% across groups.</p>
</section>
<section id="c-1" class="level3">
<h3 class="anchored" data-anchor-id="c-1">c)</h3>
<p>Are <em>education</em> and <em>ofjobs</em> balanced across race?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>bm <span class="sc">|&gt;</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(race)<span class="sc">|&gt;</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">prop_educ =</span> <span class="fu">mean</span>(education), <span class="at">prop_ofjobs =</span> <span class="fu">mean</span>(ofjobs))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  race  prop_educ prop_ofjobs
  &lt;chr&gt;     &lt;dbl&gt;       &lt;dbl&gt;
1 b          3.62        3.66
2 w          3.62        3.66</code></pre>
</div>
</div>
<p>Yes, they are.</p>
</section>
<section id="d" class="level3">
<h3 class="anchored" data-anchor-id="d">d)</h3>
<p>Compute the mean and standard deviation of <em>yearsexp</em> by race. Comment on your findings.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>bm <span class="sc">|&gt;</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(race)<span class="sc">|&gt;</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_yearsexp =</span> <span class="fu">mean</span>(yearsexp), <span class="at">sd_yearsexp =</span> <span class="fu">sd</span>(yearsexp))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  race  mean_yearsexp sd_yearsexp
  &lt;chr&gt;         &lt;dbl&gt;       &lt;dbl&gt;
1 b              7.83        5.01
2 w              7.86        5.08</code></pre>
</div>
</div>
<p>This means that not only is mean of years of experience across races the same, but that also the distribution of years of experience around the mean has the same variability, such that we know it is not the case that more individuals the black group have experiences close to the mean of 7.8 years than the white group, and vice versa.</p>
</section>
<section id="e-why-do-we-care-if-sex-education-ofjobs-computerskills-and-yearsexp-are-balanced-across-race" class="level3">
<h3 class="anchored" data-anchor-id="e-why-do-we-care-if-sex-education-ofjobs-computerskills-and-yearsexp-are-balanced-across-race">e) Why do we care if <em>sex</em>, <em>education</em>, <em>ofjobs</em>, <em>computerskills</em>, and <em>yearsexp</em> are balanced across race?</h3>
<p>We care because if they are not balanced, then any differences in outcomes (callbacks) may be due to these factors, and not factors directly related to race itself. These variables listed are proxys for if randomization process has eliminated differences in all unobserved factors which may influence the outcome variable. In other words we are testing for the orthogonality condition to hold between the error term and the treatment variable in a casual model.</p>
</section>
<section id="f" class="level3">
<h3 class="anchored" data-anchor-id="f">f)</h3>
<p>Is <em>computerskills</em> balanced across <em>sex</em>? What about <em>education</em>? What’s going on here? Is it a problem?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>bm <span class="sc">|&gt;</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex)<span class="sc">|&gt;</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_computerskills =</span> <span class="fu">mean</span>(computerskills),</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">mean_education =</span> <span class="fu">mean</span>(education))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  sex   mean_computerskills mean_education
  &lt;chr&gt;               &lt;dbl&gt;          &lt;dbl&gt;
1 f                   0.868           3.58
2 m                   0.662           3.73</code></pre>
</div>
</div>
<p>As we can see, it seems as though females have higher computer skills and low education on average. To investigate why this is: we first see that in section II C of the paper the experimenters use male and female names for sales jobs but nearly exclusively female names for administrative jobs to increase callback rates. To verify this I choose <em>secretary</em>, <em>supervisor</em>, and <em>offsupport</em> as three proxies for adminstrative jobs present in the dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>bm <span class="sc">|&gt;</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex)<span class="sc">|&gt;</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">sum</span>(secretary), <span class="fu">sum</span>(supervisor), <span class="fu">sum</span>(offsupport))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  sex   `sum(secretary)` `sum(supervisor)` `sum(offsupport)`
  &lt;chr&gt;            &lt;dbl&gt;             &lt;dbl&gt;             &lt;dbl&gt;
1 f                 1591               359               556
2 m                   30                17                22</code></pre>
</div>
</div>
<p>Indeed, we find that for each of these variables there is no men included but exclusively female. Let’s then investigate the <em>computerskills</em> and <em>education</em> for each of these jobs, compared to the rest of the sample (all other jobs).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>bm <span class="sc">|&gt;</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(secretary)<span class="sc">|&gt;</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">mean</span>(computerskills), <span class="fu">mean</span>(education))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  secretary `mean(computerskills)` `mean(education)`
      &lt;dbl&gt;                  &lt;dbl&gt;             &lt;dbl&gt;
1         0                  0.752              3.66
2         1                  0.957              3.54</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>bm <span class="sc">|&gt;</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(supervisor)<span class="sc">|&gt;</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">mean</span>(computerskills), <span class="fu">mean</span>(education))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  supervisor `mean(computerskills)` `mean(education)`
       &lt;dbl&gt;                  &lt;dbl&gt;             &lt;dbl&gt;
1          0                  0.811              3.63
2          1                  0.934              3.52</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>bm <span class="sc">|&gt;</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(offsupport)<span class="sc">|&gt;</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">mean</span>(computerskills), <span class="fu">mean</span>(education))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  offsupport `mean(computerskills)` `mean(education)`
       &lt;dbl&gt;                  &lt;dbl&gt;             &lt;dbl&gt;
1          0                  0.806              3.64
2          1                  0.926              3.47</code></pre>
</div>
</div>
<p>We find that indeed, those who get these jobs have on average higher computer efficiency and lower education. Since the people who go for these jobs are majority women, this would explain this phenomena of unbalanced <em>computerskills</em> and <em>education</em> across <em>sex</em>. This is not a problem because we only need the other variables to be balanced when divided into race. In other words, we only need all other variables to be orthogonal with the treatment, which in this case is race, not sex. We have verified this type of balancedness (across races) in the previous parts.</p>
</section>
</section>
<section id="q5" class="level2">
<h2 class="anchored" data-anchor-id="q5">Q5</h2>
<section id="a-3" class="level3">
<h3 class="anchored" data-anchor-id="a-3">a)</h3>
<p>Calculate the average callback rate for all resumes in <em>bm</em>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(bm[[<span class="st">"call"</span>]]) <span class="sc">*</span> <span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8.049281</code></pre>
</div>
</div>
<p>This corresponds to the 8.05 percent callback rate in the table.</p>
</section>
<section id="b-3" class="level3">
<h3 class="anchored" data-anchor-id="b-3">b)</h3>
<p>Calculate the average callback rates separately for resumes with “white-sounding” and “black-sounding” names. What do your results suggest?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>bm <span class="sc">|&gt;</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(race)<span class="sc">|&gt;</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">mean</span>(call))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  race  `mean(call)`
  &lt;chr&gt;        &lt;dbl&gt;
1 b           0.0645
2 w           0.0965</code></pre>
</div>
</div>
<p>These results corresponds to the results in the first row of table 1 in the paper, and suggests that controlling for all other factors, having a white-sounding name results in a 3% increase in callback likelihood than a black-sounding one.</p>
</section>
<section id="c-2" class="level3">
<h3 class="anchored" data-anchor-id="c-2">c)</h3>
<p>Repeat part 2, but calculate the average rates for each combination of race and sex. What do your results suggest?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>bm <span class="sc">|&gt;</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(race, sex)<span class="sc">|&gt;</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">mean</span>(call))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'race'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
# Groups:   race [2]
  race  sex   `mean(call)`
  &lt;chr&gt; &lt;chr&gt;        &lt;dbl&gt;
1 b     f           0.0663
2 b     m           0.0583
3 w     f           0.0989
4 w     m           0.0887</code></pre>
</div>
</div>
<p>The results again align with the table, and seem to suggest that females on average get more callbacks than males. However, this cannot be interpreted the same way that race could causally because sex is not randomly assigned: there are some jobs where the majority of applications (that the researchers choose) were female, which means that it is not random assignment.</p>
</section>
</section>
<section id="q6" class="level2">
<h2 class="anchored" data-anchor-id="q6">Q6</h2>
<section id="test-the-null-hypothesis-that-there-is-no-difference-in-callback-rates-across-black-and-white-sounding-names-against-the-two-sided-alternative.-comment-on-your-results." class="level3">
<h3 class="anchored" data-anchor-id="test-the-null-hypothesis-that-there-is-no-difference-in-callback-rates-across-black-and-white-sounding-names-against-the-two-sided-alternative.-comment-on-your-results.">Test the null hypothesis that there is no difference in callback rates across black and white-sounding names against the two-sided alternative. Comment on your results.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>black_callback <span class="ot">&lt;-</span> <span class="fu">pull</span>(<span class="fu">filter</span>(bm, race <span class="sc">==</span> <span class="st">"b"</span>), call)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>white_callback <span class="ot">&lt;-</span> <span class="fu">pull</span>(<span class="fu">filter</span>(bm, race <span class="sc">==</span> <span class="st">"w"</span>), call)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(black_callback, white_callback, <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  black_callback and white_callback
t = -4.1147, df = 4711.6, p-value = 3.943e-05
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -0.04729503 -0.01677067
sample estimates:
 mean of x  mean of y 
0.06447639 0.09650924 </code></pre>
</div>
</div>
<p>Therefore, since our hypothesis is that:</p>
<ul>
<li><p>Null Hypothesis: There is no difference in means between black and white-sounding names.</p></li>
<li><p>Alternative Hypothesis: The true difference in means is not equal to 0.</p></li>
</ul>
<p>these results suggest that there is a statistically significant difference in callback rates between black and white-sounding names, with white-sounding names having a higher mean callback rate than black-sounding names. In particular, there is a substantial difference between the mean of the two groups, with a p-value well below the conventional significance level of 0.05.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">© Copyright 2024, Toby Wang</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">Built with <a href="https://quarto.org/">Quarto</a></div>
  </div>
</footer>



</body></html>